name: CI
on:
  push:
    branches: [ "*" ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Code quality
      run: |
        flake8 cloudflare_pages/ --ignore E501,F405,F403

    - name: Run tests
      run: |
        pytest --pyargs cloudflare_pages
